[package]
name = "df"
version = "0.0.1"
authors = []

[lib]
name = "uu_df"
path = "df.rs"

[dependencies]
clap = "2.24.1"
libc = "0.2.26"
uucore = "0.0.1"

[target.'cfg(target_os = "windows")'.dependencies]
kernel32-sys = "*"
winapi = "*"

[[bin]]
name = "df"
path = "main.rs"
